[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-ObjC"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-ObjC"]

[target.aarch64-apple-ios]
rustflags = ["-C", "link-args=-ObjC"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "link-args=-ObjC"]

[profile.dev]
opt-level = 0         # Disable optimizations to make debugging easier
debug = true          # Include debug symbols for more detailed debugging
debug-assertions = true  # Enable debug assertions for better error detection
overflow-checks = true   # Enable integer overflow checks
lto = false           # Disable LTO for faster compilation times
strip = false         # Don't strip symbols so you can fully debug